-- Fixed SQL from sample.txt with UPSERT handling
-- Generated on: 2025-06-11T01:41:22.109Z
-- Total resources: 196
-- This version uses ON CONFLICT DO UPDATE to handle duplicates

-- Insert all resources from sample.txt with UPSERT
INSERT INTO resources (domain, url, domain_authority, category, cost, notes, is_active, created_at, updated_at) VALUES
('flameitup.net', 'https://flameitup.net', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('creati.ai', 'https://creati.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('hiaitools.com', 'https://hiaitools.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aistage.net', 'https://aistage.net', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('soai.tools', 'https://soai.tools', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('dang.ai', 'https://dang.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('futur-ia.com', 'https://futur-ia.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolnet.com', 'https://aitoolnet.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('dokeyai.com', 'https://dokeyai.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aipure.ai', 'https://aipure.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ypforai.com', 'https://ypforai.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aimonstr.com', 'https://aimonstr.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('promoteproject.com', 'https://promoteproject.com', 0, 'project-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('saasworthy.com', 'https://saasworthy.com', 0, 'saas-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('alayaai.site', 'https://alayaai.site', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('fivetaco.com', 'https://fivetaco.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('whattheai.tech', 'https://whattheai.tech', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aiailist.com', 'https://aiailist.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('futuretools.io', 'https://futuretools.io', 0, 'tools-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('navs.site', 'https://navs.site', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('seekais.com', 'https://seekais.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolly.com', 'https://aitoolly.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('findmyaitool.com', 'https://findmyaitool.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('magicbox.tools', 'https://magicbox.tools', 0, 'tools-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('phcopilot.ai', 'https://phcopilot.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('allinai.tools', 'https://allinai.tools', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('insidr.ai', 'https://insidr.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('dir2ai.com', 'https://dir2ai.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('viesearch.com', 'https://viesearch.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolbox.tools', 'https://aitoolbox.tools', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ainavhub.com', 'https://ainavhub.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gpt4oo.com', 'https://gpt4oo.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ai-findr.com', 'https://ai-findr.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('genaiprism.site', 'https://genaiprism.site', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolsexplorer.org', 'https://aitoolsexplorer.org', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('maomaoyu.coffee', 'https://maomaoyu.coffee', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('right-ai.com', 'https://right-ai.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('toolsapp.cc', 'https://toolsapp.cc', 0, 'tools-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aieasy.life', 'https://aieasy.life', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('whatisaitools.com', 'https://whatisaitools.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aiai.tools', 'https://aiai.tools', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('seektop.ai', 'https://seektop.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('smartaitools.run', 'https://smartaitools.run', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitooltrek.com', 'https://aitooltrek.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('nextool.ai', 'https://nextool.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('zzo.ai', 'https://zzo.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('seewhatnewai.com', 'https://seewhatnewai.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('launchtory.com', 'https://launchtory.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('sideprojectors.com', 'https://sideprojectors.com', 0, 'project-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('indiehackernews.com', 'https://indiehackernews.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('goodaitools.com', 'https://goodaitools.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('directories.wiki', 'https://directories.wiki', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('lachief.io', 'https://lachief.io', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('txc.qq.com', 'https://txc.qq.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('toucu.ai', 'https://toucu.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('nextgentool.io', 'https://nextgentool.io', 0, 'tools-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aidirectory.org', 'https://aidirectory.org', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('toolscout.ai', 'https://toolscout.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ai-toolify.com', 'https://ai-toolify.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gptforge.net', 'https://gptforge.net', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('humanwithai.top', 'https://humanwithai.top', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('saasbaba.com', 'https://saasbaba.com', 0, 'saas-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoprank.com', 'https://aitoprank.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gptscollection.xyz', 'https://gptscollection.xyz', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitooldr.com', 'https://aitooldr.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aimarketing.directory', 'https://aimarketing.directory', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('igniter.ai', 'https://igniter.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('journaliststoolbox.ai', 'https://journaliststoolbox.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('startupaitools.com', 'https://startupaitools.com', 0, 'startup-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolsguide.com', 'https://aitoolsguide.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('free-ai-tools-directory.com', 'https://free-ai-tools-directory.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ainavigationsite.com', 'https://ainavigationsite.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('findaitools.co', 'https://findaitools.co', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('humanornot.co', 'https://humanornot.co', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('nextgentools.me', 'https://nextgentools.me', 0, 'tools-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('airegisters.com', 'https://airegisters.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolsup.com', 'https://aitoolsup.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('chataiapps.com', 'https://chataiapps.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('tools.so', 'https://tools.so', 0, 'tools-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('trustiner.com', 'https://trustiner.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('faind.ai', 'https://faind.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('futureagitools.com', 'https://futureagitools.com', 0, 'tools-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('indieai.co', 'https://indieai.co', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolhub.net', 'https://www.aitoolhub.net/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('funfun.tools', 'https://www.funfun.tools/', 0, 'tools-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aigo.tools', 'https://aigo.tools/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('detectortools.ai', 'https://detectortools.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gptnocode.com', 'https://gptnocode.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('infrabase.ai', 'https://infrabase.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('theaigeneration.com', 'https://theaigeneration.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolslist.top', 'https://aitoolslist.top', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('autoais.com', 'https://autoais.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('freeaitools.fyi', 'https://freeaitools.fyi', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('spaceofai.tools', 'https://spaceofai.tools', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolbox.fyi', 'https://aitoolbox.fyi', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('fuliba123.net', 'https://fuliba123.net', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kuakua.app', 'https://kuakua.app', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('tools-ai.xyz', 'https://tools-ai.xyz', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aiex.me', 'https://aiex.me', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('forms.gle', 'https://forms.gle', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('hao.logosc.cn', 'https://hao.logosc.cn', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('startupstash.com', 'https://startupstash.com', 0, 'startup-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('tap4.ai', 'https://tap4.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('saasaitools.com', 'https://saasaitools.com', 0, 'saas-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('toolpilot.ai', 'https://toolpilot.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('startupbase.io', 'https://startupbase.io', 0, 'startup-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('basedtools.ai', 'https://basedtools.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolmall.com', 'https://aitoolmall.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('marsx.dev', 'https://marsx.dev', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('nocodelist.co', 'https://nocodelist.co', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('news.bensbites.co', 'https://news.bensbites.co', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('toolsfine.com', 'https://toolsfine.com', 0, 'tools-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('launched.io', 'https://launched.io', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolsdirectory.com', 'https://aitoolsdirectory.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('openfuture.ai', 'https://openfuture.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('library.phygital.plus', 'https://library.phygital.plus', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('nanai.tools', 'https://nanai.tools', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('topapps.ai', 'https://topapps.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('tools.robingood.com', 'https://tools.robingood.com', 0, 'tools-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('app.10words.io', 'https://app.10words.io', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('bestaitoolsforthat.com', 'https://bestaitoolsforthat.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aibest.tools', 'https://aibest.tools', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('devtoolset.net', 'https://devtoolset.net', 0, 'tools-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ailib.ru', 'https://ailib.ru', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolguru.com', 'https://aitoolguru.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('favird.com', 'https://favird.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aivalley.ai', 'https://aivalley.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('bizbot.com', 'https://bizbot.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('poweredbyai.app', 'https://poweredbyai.app', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('toollist.ai', 'https://toollist.ai', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('betteraitools.com', 'https://betteraitools.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ai-hunter.io', 'https://ai-hunter.io', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitogrow.com', 'https://aitogrow.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('canopydirectory.com', 'https://canopydirectory.com', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('insanelycooltools.com', 'https://insanelycooltools.com', 0, 'tools-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('generativetools.ai', 'https://generativetools.ai/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('youraitool.com', 'https://youraitool.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('toolsforhumans.ai', 'https://www.toolsforhumans.ai/tools-database', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('toolhunter.ai', 'https://www.toolhunter.ai/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('superaitools.io', 'https://www.superaitools.io/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('stork.ai', 'https://www.stork.ai/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('saashub.com', 'https://www.saashub.com/', 0, 'saas-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('listedai.co', 'https://www.listedai.co/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('launchingnext.com', 'https://www.launchingnext.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('joinly.xyz', 'https://www.joinly.xyz/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aishowcase.io', 'https://www.aishowcase.io/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ainave.com', 'https://www.ainave.com/tools', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aihub.cn', 'https://www.aihub.cn/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aigotools.com', 'https://www.aigotools.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aifinesse.com', 'https://www.aifinesse.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aibucket.io', 'https://www.aibucket.io/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aibluebook.com', 'https://www.aibluebook.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ai-navigation.net', 'https://www.ai-navigation.net/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('affordhunt.com', 'https://www.affordhunt.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('woy.ai', 'https://woy.ai/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('waildworld.com', 'https://waildworld.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('victrays.com', 'https://victrays.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('tooldirectory.ai', 'https://tooldirectory.ai/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('thataicollection.com', 'https://thataicollection.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('telegra.ph', 'https://telegra.ph/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('t0ai.com', 'https://t0ai.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('supertools.therundown.ai', 'https://supertools.therundown.ai/submit', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('stratup.ai', 'https://stratup.ai/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('startupbuffer.com', 'https://startupbuffer.com/', 0, 'startup-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('softgist.com', 'https://softgist.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('reviewai.net', 'https://reviewai.net/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('obt.ai', 'https://obt.ai/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('news.bensbites.com', 'https://news.bensbites.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('navai.me', 'https://navai.me/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('iuu.ai', 'https://iuu.ai/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('hdrobots.com', 'https://hdrobots.com/submit-ai-tool', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('futurepard.com', 'https://futurepard.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('funai.online', 'https://funai.online/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('freework.ai', 'https://freework.ai/suggest', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('foundr.ai', 'https://foundr.ai/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('forit.ai', 'https://forit.ai/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('every-ai.com', 'https://every-ai.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('devhunt.org', 'https://devhunt.org/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('betalist.com', 'https://betalist.com/topics/ai-tools', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('bai.tools', 'https://bai.tools/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('altern.ai', 'https://altern.ai/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('allthingsai.com', 'https://allthingsai.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aiwith.me', 'https://aiwith.me/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoptools.com', 'https://aitoptools.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolsmasters.com', 'https://aitoolsmasters.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolsmarketer.com', 'https://aitoolsmarketer.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolslist.io', 'https://aitoolslist.io/submit-ai-tool/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolshunter.com', 'https://aitoolshunter.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolsforbest.com', 'https://aitoolsforbest.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitoolcenter.com', 'https://aitoolcenter.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aitool.tools', 'https://aitool.tools/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aiscout.net', 'https://aiscout.net/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aijustworks.com', 'https://aijustworks.com/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('aiinfinity-meetpatel.notion.site', 'https://aiinfinity-meetpatel.notion.site/AI-Infinity-AI-Tools-Directory-0da673c487124ea2b6f8ebe59b75a231', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ai.navs.site', 'https://ai.navs.site/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ai-hub.tools', 'https://ai-hub.tools/', 0, 'ai-directory', 0, 'From sample.txt import', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (domain) DO UPDATE SET
    url = EXCLUDED.url,
    domain_authority = EXCLUDED.domain_authority,
    category = EXCLUDED.category,
    cost = EXCLUDED.cost,
    notes = EXCLUDED.notes,
    updated_at = CURRENT_TIMESTAMP;

-- Summary of inserted/updated resources
SELECT 
    category,
    COUNT(*) as count,
    AVG(domain_authority) as avg_da,
    COUNT(*) FILTER (WHERE cost = 0) as free_submissions,
    COUNT(*) FILTER (WHERE cost > 0) as paid_submissions
FROM resources 
GROUP BY category
ORDER BY count DESC;

-- Show total count
SELECT COUNT(*) as total_resources FROM resources; 