'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight, Check, Clipboard, LogOut, Plus, RefreshCw, Play, Save, Search } from 'lucide-react';
import { dayInMelbourne, httpUrl, type OperationsReport, type Row } from '@/lib/backlink-operations-core';
import './operations.css';
const labels: Record<string,string> = {free:'免费可投递',exchange:'互换可投递',confirmed:'历史已确认 · 条件待核实',pending:'暂未验证通过',unavailable:'暂不可投递',listed:'收录通过',legacy_live:'历史已上线 · 待复核',missing_link:'未发现外链',unreachable:'暂时无法访问',removed:'疑似已移除',requested:'已投递 · 待审核',placed:'已放置',live:'历史已上线',rejected:'已拒绝',reserved:'待执行',submitted:'投递成功',failed:'投递失败',uncertain:'结果不明确'};
const time = (v: unknown) => v ? new Date(String(v)).toLocaleString('zh-CN',{timeZone:'Australia/Melbourne',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}) : '未记录';
function External({url,children}:{url?:string;children:React.ReactNode}) { const safe=httpUrl(url); return safe ? <a href={safe} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={13}/></a> : <span>{children}</span>; }
function Status({value}:{value:string}) {return <span className={`ops-status ops-status-${value}`}>{labels[value] || value}</span>;}
export default function OperationsPage() {
  const [token,setToken]=useState('');
  const [password,setPassword]=useState('');
  const [data,setData]=useState<{ready:boolean;archived:boolean;report:OperationsReport;savedAt?:string}|null>(null);
  const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
  const [day,setDay]=useState(dayInMelbourne()),[snapshot,setSnapshot]=useState('');
  const [tab,setTab]=useState('overview'),[siteId,setSiteId]=useState('');
  const [search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(1);
  const [dialog,setDialog]=useState<Row|null>(null),[form,setForm]=useState<Row>({});
  const sequence=useRef(0);
  const modal=useRef<HTMLDialogElement>(null);
  useEffect(()=>{if(dialog && modal.current && !modal.current.open)modal.current.showModal();},[dialog]);
  const report=data?.report;
  const readonly=!!data?.archived || day!==dayInMelbourne();
  const canWrite=!!data?.ready && !readonly && !busy;
  const load=useCallback(async()=>{
    if(!token)return;
    const seq=++sequence.current;setLoading(true);setError('');
    try {const response=await fetch(`/api/operations?day=${day}${snapshot?`&snapshot=${snapshot}`:''}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'}); const result=await response.json(); if(!response.ok)throw Error(result.message);if(seq===sequence.current)setData(result);}
    catch(e){if(seq===sequence.current){setError(e instanceof Error?e.message:'读取失败');setData(null);}}
    finally{if(seq===sequence.current)setLoading(false);}
  },[token,day,snapshot]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{setPage(1);},[search,filter,tab,siteId]);
  async function mutate(body:Row) {
    if(!canWrite)return;setBusy(true);setError('');setMessage('');
    try {const response=await fetch('/api/operations',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.message);setMessage(result.message);setDialog(null);await load();}
    catch(e){setError(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}
  }
  function open(kind:string,row:Row={}){setDialog({kind,...row});setForm({result:kind==='check'?'pending':kind==='review'?'pending':'uncertain',evidenceUrl:row.liveUrl || row.submissionUrl || '',entryUrl:row.url || '',targetUrl:'',note:'',rel:'',urls:''});}
  function selectTab(next:string){setTab(next);setFilter('all');setSearch('');}
  const site=report?.sites.find(s=>s.id===siteId) || report?.sites[0];
  const records=useMemo(()=> (site?.records || []).filter(r=> (!search || `${r.domain} ${r.note}`.toLowerCase().includes(search.toLowerCase())) && (filter==='all' || (filter==='today'?dayInMelbourne(r.submittedAt)===report?.day:filter==='listed'?r.verification==='listed':r.verification!=='listed'))),[site,search,filter,report?.day]);
  const resources=useMemo(()=> (report?.resources || []).filter(r=> (!search || `${r.domain} ${r.note}`.toLowerCase().includes(search.toLowerCase())) && (filter==='all' || (filter==='ready'?['free','exchange'].includes(r.status):filter==='pending'?['pending','confirmed'].includes(r.status):r.status===filter))),[report,search,filter]);
  async function copyTask(){
    const run=report?.runs.find(r=>r.status==='open');
    const text=`执行 Backlink 运营台手动任务${run?` ${run.id}`:''}。读取项目根目录 docs/operations.md 和 /api/operations 当前数据库状态；墨尔本今天每个网站成功投递恰好 5 个，已有成功计入额度；先核对 reserved/uncertain 待办防重复，逐项保存实际结果，失败补位。只处理免费或已确认条件的互换，不付款，不发送未经授权的站外消息。检查对方网站是否收录，不检查 Google。最后保存日报并报告每站缺口。不得把创建待办当作实际投递。`;
    try{await navigator.clipboard.writeText(text);setMessage('执行指令已复制，可以发送给 Codex 手动开始。');}catch{setError('无法访问剪贴板，请在 Codex 中输入“执行今天的 Backlink 运营任务”。');}
  }
  return <main className="ops-shell">
    <header className="ops-header"><div><Link href="/" className="ops-back"><ArrowLeft size={14}/> Backlink Tracker</Link><h1>外链运营台<span>手动执行</span></h1><p>每站每天 5 次成功投递 · Australia/Melbourne</p></div>{token && <button className="ops-icon" title="退出" onClick={()=>{sequence.current++;setToken('');setPassword('');setData(null);setDialog(null);}}><LogOut size={18}/></button>}</header>
    {!token ? <form className="ops-login" onSubmit={e=>{e.preventDefault();setToken(password.trim());setPassword('');}}><h2>连接现有工作区</h2><p>使用现有 Backlink Desk 访问令牌。令牌仅保留在当前页面内存，刷新后需要重新输入。</p><label>访问令牌<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="off"/></label><button className="ops-primary" type="submit">进入运营台</button></form> : <>
    <div className="ops-toolbar"><div className="ops-date"><label>报表日期 <input aria-label="报表日期" type="date" value={day} max={dayInMelbourne()} onChange={e=>{if(e.target.value){setDay(e.target.value);setSnapshot('');}}}/></label><button onClick={()=>void load()} disabled={loading||busy} aria-label="刷新"><RefreshCw size={16}/></button></div><div className="ops-actions"><button disabled={!canWrite} onClick={()=>void mutate({action:'snapshot'})}><Save size={15}/>保存日报</button><button className="ops-primary" disabled={!canWrite} onClick={()=>void mutate({action:'start'})}><Play size={15}/>准备／补充今日任务</button><button disabled={!report||readonly} onClick={()=>void copyTask()}><Clipboard size={15}/>复制执行指令</button></div></div>
    {error&&<p role="alert" className="ops-notice ops-error">{error}</p>}{message&&<p role="status" className="ops-notice">{message}</p>}
    {loading&&<p role="status">正在读取数据库…</p>}
    {data&&!data.ready&&<p className="ops-notice">当前为只读预览：历史数据已接入，运营台迁移尚未应用，任务与写入功能暂不可用。</p>}
    {readonly&&<p className="ops-notice">{data?.archived?`已保存日报 · ${time(data.savedAt)} · 此版本不会随后续结果改变`:'此日期尚未选择已保存日报：下方为当前状态，今日数量按所选日期统计。' } <button onClick={()=>{setSnapshot('');setDay(dayInMelbourne());}}>返回今天</button></p>}
    {report&&<><nav className="ops-tabs" aria-label="运营视图">{[['overview','每日总览'],['websites','网站投递'],['resources','资源验证'],['tasks','待处理事项']].map(([value,label])=><button key={value} aria-current={tab===value?'page':undefined} onClick={()=>selectTab(value)}>{label}</button>)}</nav>
    {tab==='overview'&&<><div className="ops-site-grid">{report.sites.map(s=><button key={s.domain} className="ops-site-card" onClick={()=>{setSiteId(s.id);selectTab('websites');}}><div className="ops-eyebrow">{s.domain}<ArrowUpRight size={16}/></div><h2>{s.name}</h2><div className="ops-count">{s.today}<small> / 5</small></div><div className="ops-meter"><i style={{width:`${Math.min(100,s.today/5*100)}%`}}/></div><p>{s.missing?'数据库中尚未找到此网站':!s.active?'网站已停用':s.today===5?'今日达标':s.today>5?'历史记录超额，请核实':`距目标还差 ${s.remaining} 个`}</p><footer><span>{s.records.length} 已投递</span><span>{s.records.filter(r=>r.verification==='listed').length} 收录通过</span></footer></button>)}</div>
      <div className="ops-summary-grid"><section className="ops-panel"><h2>资源准备情况</h2><dl>{[['免费／互换可投递',report.resources.filter(r=>['free','exchange'].includes(r.status)).length],['待验证／条件待核实',report.resources.filter(r=>['pending','confirmed'].includes(r.status)).length],['暂不可投递',report.resources.filter(r=>r.status==='unavailable').length]].map(([label,n])=><div key={label}><dt>{label}</dt><dd>{n}</dd></div>)}</dl><p>新资源追加队尾。历史确认记录保留，免费或互换条件核实后参与任务分配。</p></section><section className="ops-panel"><h2>已保存日报</h2><p>每次记录结果都会保存新版本；没有触发的日期不会自动生成报表。</p><div className="ops-snapshots">{report.reports.filter(r=>String(r.day).slice(0,10)===day || dayInMelbourne(r.created_at)===day).slice(0,30).map(r=><button key={r.id} onClick={()=>setSnapshot(String(r.id))}>{time(r.created_at)} <span>查看此版本 →</span></button>)}{!report.reports.some(r=>dayInMelbourne(r.created_at)===day)&&<p>此日期暂无已保存版本。</p>}</div></section></div>
      <section className="ops-panel"><h2>执行方式</h2><p>准备任务会保存待办，不会在后台自动提交。复制执行指令发送给 Codex 后，由 Codex 执行并记录结果；你也可以在待处理事项中记录手动处理的结果。</p><p>只有有证据的成功提交计入每日目标。结果不明确的任务保留占位，先核实再继续。</p></section></>}
    {tab==='websites'&&<><div className="ops-site-switch">{report.sites.map(s=><button key={s.domain} aria-pressed={s.domain===site?.domain} onClick={()=>setSiteId(s.id)}>{s.name}<span>{s.today}/5</span></button>)}</div><div className="ops-list-head"><div><h2>{site?.name} · 投递记录</h2><p>{site?.unknownDates || 0} 条历史记录缺少投递日期，不擅自计入今天。</p></div><Link href={`/website/${site?.id || ''}`}>管理网站资料 →</Link></div><div className="ops-filters"><label><Search size={16}/><input aria-label="搜索投递记录" placeholder="搜索资源或备注" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="投递状态筛选" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部已投递</option><option value="today">今日投递</option><option value="listed">收录通过</option><option value="pending">暂未验证通过</option></select></div><div className="ops-table-wrap"><table><thead><tr><th>资源</th><th>投递时间</th><th>收录结果</th><th>证据与备注</th><th>操作</th></tr></thead><tbody>{records.slice((page-1)*50,page*50).map(r=><tr key={r.id}><td><External url={r.submissionUrl || `https://${r.domain}`}>{r.domain}</External><small>{labels[r.status]||r.status}</small></td><td>{time(r.submittedAt)}</td><td><Status value={r.verification}/><small>检查：{time(r.checkedAt)}</small></td><td>{r.liveUrl&&<External url={r.liveUrl}>对方详情页</External>}<p>{r.note || '暂无检查证据'}</p>{r.rel&&<small>rel: {r.rel}</small>}<details><summary>状态历史</summary>{r.history.map((h:Row,i:number)=><p key={i}>{time(h.at)} · {labels[h.status]||h.status} · {h.note}</p>)}</details></td><td><button disabled={!canWrite} onClick={()=>open('check',{...r,websiteId:site?.id})}>记录检查</button></td></tr>)}</tbody></table>{!records.length&&<p className="ops-empty">没有符合条件的投递记录。</p>}</div></>}
    {tab==='resources'&&<><div className="ops-list-head"><div><h2>资源验证队列</h2><p>按首次加入时间排列。筛选结果不会改变队列顺序。</p></div><button className="ops-primary" disabled={!canWrite} onClick={()=>open('add')}><Plus size={16}/>添加资源</button></div><div className="ops-filters"><label><Search size={16}/><input aria-label="搜索资源" placeholder="搜索域名或条件" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="资源状态筛选" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部资源</option><option value="ready">免费／互换可投递</option><option value="pending">待验证／条件待核实</option><option value="unavailable">暂不可投递</option></select><span>{resources.length} 个</span></div><div className="ops-table-wrap"><table><thead><tr><th>队列 / 资源</th><th>验证状态</th><th>验证依据与条件</th><th>各网站投递</th><th>操作</th></tr></thead><tbody>{resources.slice((page-1)*50,page*50).map(r=><tr key={r.id}><td><small>#{report.resources.indexOf(r)+1} · {time(r.createdAt)}</small><External url={r.url || `https://${r.domain}`}>{r.domain}</External></td><td><Status value={r.status}/><small>{time(r.checkedAt)}</small></td><td><p>{r.note || '暂无验证依据'}</p>{r.screeningSummary&&<details><summary>原筛选结果</summary><p>{r.screeningSummary}</p></details>}</td><td>{report.sites.map(s=>{const existing=s.records.find(v=>v.resourceId===r.resourceId);return <small key={s.domain}>{s.name}: {existing ? labels[existing.verification] : '未投递'}</small>;})}</td><td><button disabled={!canWrite} onClick={()=>open('review',r)}>记录验证</button></td></tr>)}</tbody></table>{!resources.length&&<p className="ops-empty">没有符合条件的资源。</p>}</div></>}
    {['websites','resources'].includes(tab)&&<div className="ops-pagination"><button disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</button><span>第 {page} 页 · 共 {Math.max(1,Math.ceil((tab==='websites'?records.length:resources.length)/50))} 页</span><button disabled={page*50>=(tab==='websites'?records.length:resources.length)} onClick={()=>setPage(page+1)}>下一页</button></div>}
    {tab==='tasks'&&<><div className="ops-list-head"><div><h2>待执行与阻塞事项</h2><p>每站占位数计入可分配额度。失败后可补充候选，结果不明确时先核实。</p></div></div>{report.sites.map(s=><section className="ops-panel" key={s.domain}><div className="ops-list-head"><h2>{s.name}<span className="ops-muted"> {s.today}/5</span></h2><span>{s.candidates.length} 个尚未投递的合格候选</span></div>{s.blockers.map((a:Row)=><div className="ops-task" key={a.id}><div><External url={report.resources.find(r=>r.resourceId===String(a.resource_id))?.url}>{a.domain}</External><small>{time(a.created_at)} · {a.note || '提交前先核对目录是否已有该产品；互换资源先检查双方条件。'}</small><code>{a.id}</code></div><Status value={a.status}/><button disabled={!canWrite} onClick={()=>open('attempt',a)}>记录结果</button></div>)}<details><summary>投递尝试历史（含失败）</summary>{s.attempts.filter((a:Row)=>!["reserved","uncertain"].includes(a.status)).map((a:Row)=><p key={a.id}>{time(a.resolved_at)} · {a.domain} · {labels[a.status]} · {a.note}</p>)}</details>{!s.blockers.length&&<p>{s.remaining===0?'今日已达标。':'暂无待办。准备任务以分配候选，或先验证更多资源。'}</p>}</section>)}<section className="ops-panel"><h2>手动任务历史</h2>{report.runs.slice(0,20).map(r=><div className="ops-task" key={r.id}><div><code>{r.id}</code><small>{time(r.created_at)} · {r.status==='open'?'未结束':'已结束'}</small></div>{r.status==='open'&&<button disabled={!canWrite} onClick={()=>void mutate({action:'close',runId:r.id})}><Check size={14}/>结束并保存</button>}</div>)}</section></>}
    </>}
    </>}
    {dialog&&<dialog ref={modal} className="ops-modal" onCancel={e=>{e.preventDefault();if(!busy)setDialog(null);}}><form role="dialog" aria-modal="true" aria-labelledby="ops-dialog-title" onSubmit={e=>{e.preventDefault();void mutate({...form,action:dialog.kind,attemptId:dialog.id,websiteId:dialog.websiteId,resourceId:dialog.resourceId,domain:dialog.domain});}}><h2 id="ops-dialog-title">{dialog.kind==='add'?'添加待验证资源':dialog.kind==='review'?'记录资源验证':dialog.kind==='check'?'记录对方收录检查':'记录实际投递结果'}</h2><p>{dialog.domain}</p>{dialog.kind==='add'?<label>每行一个网址<textarea autoFocus required rows={8} value={form.urls} onChange={e=>setForm({...form,urls:e.target.value})}/></label>:<><label>结果<select autoFocus value={form.result} onChange={e=>setForm({...form,result:e.target.value})}>{(dialog.kind==='review'?['pending','free','exchange','unavailable']:dialog.kind==='check'?['pending','listed','missing_link','unreachable','removed']:['uncertain','submitted','failed']).map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label><label>{dialog.kind==='review'?'提交入口':'对方结果页／详情页'}<input type="url" value={dialog.kind==='review'?form.entryUrl:form.evidenceUrl} onChange={e=>setForm({...form,[dialog.kind==='review'?'entryUrl':'evidenceUrl']:e.target.value})}/></label>{dialog.kind==='check'&&<><label>页面上外链的最终目标 URL<input type="url" value={form.targetUrl} onChange={e=>setForm({...form,targetUrl:e.target.value})}/></label><label>链接 rel 属性（如 nofollow）<input value={form.rel} onChange={e=>setForm({...form,rel:e.target.value})}/></label></>}<label>实际证据、条件或待处理原因<textarea required rows={4} maxLength={2000} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><p className="ops-muted">此操作保存你或 Codex 已经核实的结果，不会自动提交外站或执行页面检查。</p></>}{error&&<p role="alert" className="ops-error">{error}</p>}<div className="ops-actions"><button type="button" disabled={busy} onClick={()=>setDialog(null)}>取消</button><button className="ops-primary" disabled={busy} type="submit">{busy?'保存中…':'保存记录'}</button></div></form></dialog>}
  </main>;
}
